# SPDX-License-Identifier: MIT
# Funding configuration for Doutor
# https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/displaying-a-sponsor-button-in-your-repository

github: [md-555]
# ko_fi: md-555
# patreon: md-555
# custom: ["https://example.com/sponsor"]
